export const mockBlogPosts = [
  {
    id: 'b1',
    title: 'Building Scalable APIs with Node.js and GraphQL',
    excerpt: 'Learn how to design and build production-ready GraphQL APIs using Node.js.',
    tags: ['Node.js', 'GraphQL'],
    views: 4820,
    likes: 312,
    status: 'Published',
    readTime: '9 min read',
    publishedAt: '2025-03-10',
  },
  {
    id: 'b2',
    title: 'React 19 New Features: A Deep Dive',
    excerpt: 'Explore everything new in React 19 including compiler, server components and more.',
    tags: ['React', 'Frontend'],
    views: 7314,
    likes: 618,
    status: 'Published',
    readTime: '12 min read',
    publishedAt: '2025-03-01',
  },
  {
    id: 'b3',
    title: 'Mastering TypeScript Generics',
    excerpt: 'Deep dive into TypeScript generics with real-world examples and best practices.',
    tags: ['TypeScript', 'Programming'],
    views: 0,
    likes: 0,
    status: 'Draft',
    readTime: '10 min read',
    publishedAt: '2025-03-20',
  },
  {
    id: 'b4',
    title: 'Deploying with Docker & GitHub Actions CI/CD',
    excerpt: 'Step-by-step guide to containerize your app and automate deployments with GitHub Actions.',
    tags: ['DevOps', 'Docker'],
    views: 3190,
    likes: 224,
    status: 'Published',
    readTime: '8 min read',
    publishedAt: '2025-02-18',
  },
  {
    id: 'b5',
    title: 'CSS Grid vs Flexbox: When to Use Each',
    excerpt: 'A practical comparison of CSS Grid and Flexbox for modern layout design.',
    tags: ['CSS', 'Frontend'],
    views: 5640,
    likes: 445,
    status: 'Published',
    readTime: '7 min read',
    publishedAt: '2025-01-25',
  },
  {
    id: 'b6',
    title: 'Building Real-time Apps with WebSockets',
    excerpt: 'Implement real-time features using WebSockets, Socket.io, and Node.js.',
    tags: ['WebSocket', 'Node.js'],
    views: 0,
    likes: 0,
    status: 'Draft',
    readTime: '11 min read',
    publishedAt: '2025-03-25',
  },
];
