export const mockProjects = [
  {
    id: 'p1',
    name: 'JobFinderHub',
    description: 'Full-stack job board platform with real-time notifications, advanced filters, and employer dashboard.',
    status: 'Live',
    stars: 247,
    technologies: ['React', 'Node.js', 'MongoDB', 'Socket.io'],
    thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
    liveDemoUrl: '#',
    githubUrl: '#',
    category: 'Full-Stack',
  },
  {
    id: 'p2',
    name: 'xPadGame',
    description: 'Browser-based multiplayer game engine with WebGL rendering, physics simulation, and lobby system.',
    status: 'Live',
    stars: 189,
    technologies: ['React', 'WebGL', 'Node.js'],
    thumbnail: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?auto=format&fit=crop&w=800&q=80',
    liveDemoUrl: '#',
    githubUrl: '#',
    category: 'Game Dev',
  },
  {
    id: 'p3',
    name: 'CloudDash',
    description: 'Real-time analytics dashboard with interactive D3 charts, data export, and AWS integration.',
    status: 'In Progress',
    stars: 134,
    technologies: ['React', 'D3.js', 'AWS Lambda', 'TypeScript'],
    thumbnail: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=800&q=80',
    liveDemoUrl: '#',
    githubUrl: '#',
    category: 'Analytics',
  },
  {
    id: 'p4',
    name: 'TaskFlow',
    description: 'Agile project management tool with kanban boards, time tracking, and team collaboration features.',
    status: 'In Progress',
    stars: 63,
    technologies: ['Vue.js', 'Express', 'PostgreSQL', 'Redis'],
    thumbnail: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&w=800&q=80',
    liveDemoUrl: '#',
    githubUrl: '#',
    category: 'SaaS',
  },
  {
    id: 'p5',
    name: 'PortfolioV2',
    description: 'Personal developer portfolio with animated transitions, dark mode, and CMS-backed blog integration.',
    status: 'Live',
    stars: 412,
    technologies: ['Next.js', 'Framer Motion', 'Supabase'],
    thumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
    liveDemoUrl: '#',
    githubUrl: '#',
    category: 'Portfolio',
  },
  {
    id: 'p6',
    name: 'DevBlog CMS',
    description: 'Headless CMS-powered tech blog with MDX support, syntax highlighting, and SEO optimization.',
    status: 'Live',
    stars: 98,
    technologies: ['Next.js', 'MDX', 'GraphQL'],
    thumbnail: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?auto=format&fit=crop&w=800&q=80',
    liveDemoUrl: '#',
    githubUrl: '#',
    category: 'Content',
  },
];
